baseurl = "/"
title = "Arinze Okorji"
theme = "Blogpaper-master"
author = "Arinze Okorji"
name = "Arinze Okorji"
copyright =  "All rights reserved"
languageCode = "en"
[menu]
    [[menu.main]]
    name = 'About'
    url = '/about'
    
    [[menu.main]]
    name = 'Portfolio'
    url = '/portfolio'

    [[menu.main]]
    name = 'Articles'
    url = '/'
  
[params]
    description = 'Code tutorials'

[markup.goldmark.renderer]
  unsafe= true
    


  
